Run yaml safe load instead of plain load.
To fix the following error: 
```
# python3 train4.py train_base configs/magicpoint_shapes_pair.yaml magicpoint_synth --eval
Traceback (most recent call last):
  File "train4.py", line 134, in <module>
    config = yaml.load(f)
TypeError: load() missing 1 required positional argument: 'Loader'
```